# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('scheme', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
                ('method', models.CharField(max_length=250)),
                ('content_type', models.CharField(max_length=250)),
            ],
        ),
    ]
