# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:19
from __future__ import unicode_literals
from datetime import date

from django.db import migrations, models


def add_pub_date(apps, schema_editor):
    Book = apps.get_model("book_store", "Book")
    for book in Book.objects.all():
        book.published_date = date.today()
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(add_pub_date)
    ]
