# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
