# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 10:37
from __future__ import unicode_literals

from datetime import date

from django.db import migrations


def add_pub_date(apps, schema_editor):
    Book = apps.get_model("book_store", "Book")
    for book in Book.objects.all():
        book.published_date = date.today()
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_book_published_date'),
    ]

    operations = [
        migrations.RunPython(add_pub_date),
    ]
